=== arvind-india/indoor-navigation-system/server/wifiNode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 rel. 3 (http://www.altova.com) by Alex (Mecel AB) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="wifiNodeBlock_t">
		<xs:sequence>
			<xs:element name="_3DPosition">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="x" type="xs:float" default="0.0"/>
						<xs:element name="y" type="xs:float" default="0.0"/>
						<xs:element name="z" type="xs:float" default="0.0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="arbitraryDistance" type="xs:float" default="5.0"/>
			<xs:element name="macAddress" type="xs:string" default="ff:ff:ff:ff:ff:ff"/>
			<xs:element name="powerAtArbitraryDistance" type="xs:float" default="-65.0"/>
			<xs:element name="powerTransmit" type="xs:float" default="-50.0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="wifiNodeFloors_t">
		<xs:sequence>
			<xs:element name="wifiNodeBlock1" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock2" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock3" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock4" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock5" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock6" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock7" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock8" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock9" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock10" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock11" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock12" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock13" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock14" type="wifiNodeBlock_t"/>
			<xs:element name="wifiNodeBlock15" type="wifiNodeBlock_t"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="wifiNodeBlock">
		<xs:annotation>
			<xs:documentation>Wifi node</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="wifiNodeBlock_t"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="_3DPosition">
		<xs:annotation>
			<xs:documentation>x,y,z position</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="macAddress">
		<xs:annotation>
			<xs:documentation>macadress of wifi Node</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="powerTransmit">
		<xs:annotation>
			<xs:documentation>Power at 1 meter from wifi Node</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="powerAtArbitraryDistance">
		<xs:annotation>
			<xs:documentation>Power at arbitrary distance</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="arbitraryDistance">
		<xs:annotation>
			<xs:documentation>Arbitrary distance from wifi Node</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="wifi_Floors_t">
		<xs:sequence>
			<xs:element name="wifiFloor1" type="wifiNodeFloors_t"/>
			<xs:element name="wifiFloor2" type="wifiNodeFloors_t"/>
			<xs:element name="wifiFloor3" type="wifiNodeFloors_t"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="WifiNodes" type="wifi_Floors_t"/>
</xs:schema>

=== arvind-india/indoor-navigation-system/server/WifiNodeLCFG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2007 rel. 3 (http://www.altova.com)-->
<WifiNodes xsi:noNamespaceSchemaLocation="wifiNode.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<wifiFloor1>
		<wifiNodeBlock1>
			<_3DPosition>
				<x>1.0</x>
				<y>2.88</y>
				<z>4.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>18:D6:C7:40:33:51</macAddress>
			<powerAtArbitraryDistance>-55.4.0</powerAtArbitraryDistance>
			<powerTransmit>-43.70</powerTransmit>
		</wifiNodeBlock1>
		<wifiNodeBlock2>
			<_3DPosition>
				<x>4.919</x>
				<y>1.0</y>
				<z>4.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>8E:F5:A3:91:F5:06</macAddress>
			<powerAtArbitraryDistance>-51.58</powerAtArbitraryDistance>
			<powerTransmit>-45.40</powerTransmit>
		</wifiNodeBlock2>
		<wifiNodeBlock3>
			<_3DPosition>
				<x>3.830</x>
				<y>3.365</y>
				<z>4.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>62:01:94:5E:4A:4E</macAddress>
			<powerAtArbitraryDistance>-52.37</powerAtArbitraryDistance>
			<powerTransmit>-47.72.0</powerTransmit>
		</wifiNodeBlock3>
		<wifiNodeBlock4>
			<_3DPosition>
				<x>1.097</x>
				<y>0.975</y>
				<z>4.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>80:37:73:AC:E6:66</macAddress>
			<powerAtArbitraryDistance>-50.94</powerAtArbitraryDistance>
			<powerTransmit>-44.71</powerTransmit>
		</wifiNodeBlock4>
		<wifiNodeBlock5>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock5>
		<wifiNodeBlock6>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock6>
		<wifiNodeBlock7>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock7>
		<wifiNodeBlock8>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock8>
		<wifiNodeBlock9>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock9>
		<wifiNodeBlock10>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock10>
		<wifiNodeBlock11>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock11>
		<wifiNodeBlock12>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock12>
		<wifiNodeBlock13>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock13>
		<wifiNodeBlock14>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock14>
		<wifiNodeBlock15>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock15>
	</wifiFloor1>
	<wifiFloor2>
		<wifiNodeBlock1>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock1>
		<wifiNodeBlock2>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock2>
		<wifiNodeBlock3>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock3>
		<wifiNodeBlock4>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock4>
		<wifiNodeBlock5>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock5>
		<wifiNodeBlock6>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock6>
		<wifiNodeBlock7>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock7>
		<wifiNodeBlock8>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock8>
		<wifiNodeBlock9>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock9>
		<wifiNodeBlock10>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock10>
		<wifiNodeBlock11>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock11>
		<wifiNodeBlock12>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock12>
		<wifiNodeBlock13>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock13>
		<wifiNodeBlock14>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
			<powerTransmit>-50.0</powerTransmit>
		</wifiNodeBlock14>
		<wifiNodeBlock15>
			<_3DPosition>
				<x>0.0</x>
				<y>0.0</y>
				<z>0.0</z>
			</_3DPosition>
			<arbitraryDistance>5.0</arbitraryDistance>
			<macAddress>ff:ff:ff:ff:ff:ff</macAddress>
			<powerAtArbitraryDistance>-65.0</powerAtArbitraryDistance>
